## Sameer Ramkissoon - CSCI-415 Data Mining Project 4
### File: clean_data.ipynb

In [4]:
# Reading Algerian Forest Fires Dataset
import pandas as pd

In [5]:
df = pd.read_csv('data/Algerian_forest_fires_dataset.csv', header=1)
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

## Combining the Regions

In [6]:
# Getting the Bejaia region indices [0:122] from df
bejaia_df = df.iloc[:122]
bejaia_df['region'] = 'Bejaia'
bejaia_df.set_index('region', inplace=True)

# Performing same process with the Sidi-Bell Abbes region [124:]
sidi_bel_abbes_df = df.iloc[124:]
sidi_bel_abbes_df['region'] = 'Sidi-Bel Abbes'
sidi_bel_abbes_df.set_index('region', inplace=True)

# Combining these parts into full df
algerian_ff = pd.concat([bejaia_df, sidi_bel_abbes_df], axis=0)

In [7]:
algerian_ff.loc['Bejaia']

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Bejaia,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejaia,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejaia,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejaia,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejaia,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bejaia,26,09,2012,31,54,11,0,82,6,16.3,2.5,6.2,1.7,not fire
Bejaia,27,09,2012,31,66,11,0,85.7,8.3,24.9,4,9,4.1,fire
Bejaia,28,09,2012,32,47,14,0.7,77.5,7.1,8.8,1.8,6.8,0.9,not fire
Bejaia,29,09,2012,26,80,16,1.8,47.4,2.9,7.7,0.3,3,0.1,not fire
Bejaia,30,09,2012,25,78,14,1.4,45,1.9,7.5,0.2,2.4,0.1,not fire

In [8]:
algerian_ff.loc['Sidi-Bel Abbes']

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Sidi-Bel Abbes,01,06,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire
Sidi-Bel Abbes,02,06,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire
Sidi-Bel Abbes,03,06,2012,29,80,14,2,48.7,2.2,7.6,0.3,2.6,0.1,not fire
Sidi-Bel Abbes,04,06,2012,30,64,14,0,79.4,5.2,15.4,2.2,5.6,1,not fire
Sidi-Bel Abbes,05,06,2012,32,60,14,0.2,77.1,6,17.6,1.8,6.5,0.9,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

## Formatting columns

In [9]:
# Stripping whitespace from columns and fields
algerian_ff.columns = algerian_ff.columns.str.strip()
algerian_ff = algerian_ff.apply(lambda x: x.str.strip() if x.dtype == 'str' else x)

# Changing column names to lowercase
algerian_ff.columns = algerian_ff.columns.str.lower()

In [10]:
algerian_ff.dtypes

day            str
month          str
year           str
temperature    str
rh             str
ws             str
rain           str
ffmc           str
dmc            str
dc             str
isi            str
bui            str
fwi            str
classes        str
dtype: object

In [11]:
# Changing temperature, rh, ws, rain to float datatypes
algerian_ff = algerian_ff.astype({
    'temperature': 'float',
    'rh': 'float',
    'ws': 'float',
    'rain': 'float',
})

# Renaming above columns to match their unit of measurement
algerian_ff.rename({
    'temperature': 'temp_c',
    'rh': 'rel_humidity_percent',
    'ws': 'wind_speed_kmh',
    'rain': 'rainfall_mm',
}, axis=1, inplace=True)

algerian_ff.dtypes

day                         str
month                       str
year                        str
temp_c                  float64
rel_humidity_percent    float64
wind_speed_kmh          float64
rainfall_mm             float64
ffmc                        str
dmc                         str
dc                          str
isi                         str
bui                         str
fwi                         str
classes                     str
dtype: object

### Dropping Rows & Columns

In [12]:
algerian_ff.drop(['day', 'month', 'year'], axis=1, inplace=True)

In [13]:
algerian_ff.isnull().sum()

temp_c                  0
rel_humidity_percent    0
wind_speed_kmh          0
rainfall_mm             0
ffmc                    0
dmc                     0
dc                      0
isi                     0
bui                     0
fwi                     0
classes                 1
dtype: int64

In [14]:
algerian_ff.dropna(axis=0, subset='classes', inplace=True)
algerian_ff.isnull().sum() > 0

temp_c                  False
rel_humidity_percent    False
wind_speed_kmh          False
rainfall_mm             False
ffmc                    False
dmc                     False
dc                      False
isi                     False
bui                     False
fwi                     False
classes                 False
dtype: bool

In [15]:
algerian_ff

,temp_c,rel_humidity_percent,wind_speed_kmh,rainfall_mm,ffmc,dmc,dc,isi,bui,fwi,classes
region,,,,,,,,,,,
Bejaia,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejaia,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejaia,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejaia,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejaia,27.0,77.0,16.0,0.0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,30.0,65.0,14.0,0.0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,28.0,87.0,15.0,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,27.0,87.0,29.0,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,24.0,54.0,18.0,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,24.0,64.0,15.0,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [16]:
clean_path = 'data/algerian_forest_fires_proj4.csv'
algerian_ff.to_csv(clean_path)