## Sameer Ramkissoon - k_nearest.ipynb
Applying KNN algorithm to the cleaned Algerian forest fires dataset

In [1]:
# Imports
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_val_predict, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [2]:
# Initializing data and reading first few rows
df = pd.read_csv("data/algerian_forest_fires_proj4.csv")
df.head()

,region,temp_c,rel_humidity_percent,wind_speed_kmh,rainfall_mm,ffmc,dmc,dc,isi,bui,fwi,classes
0,Bejaia,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,Bejaia,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire
2,Bejaia,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,Bejaia,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire
4,Bejaia,27.0,77.0,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire

In [3]:
# Printing the shape of the dataset (243 instances only)
df.shape

(243, 12)

### Getting Training & Testing Data
- Dropping the region column (only focusing on numerical attributes and index codes for forest fires)
- Using K-Fold Cross Validation due to low number of instances

In [4]:
# Dropping region column
tested_df = df.drop('region', axis=1).copy()
tested_df.head()

,temp_c,rel_humidity_percent,wind_speed_kmh,rainfall_mm,ffmc,dmc,dc,isi,bui,fwi,classes
0,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire
2,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire
4,27.0,77.0,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire

In [5]:
# Using full dataset for training & testing
fire_data_x = tested_df.drop('classes', axis=1)
fire_data_y = tested_df['classes']

# Creating k-folds with 5 splits (4 train, 1 test) and shuffle instances
cross_validation = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [6]:
# Using Pipeline to scale the KNN
# Attribute value ranges are very different (requires scaling)
knn_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])

# Parameters for KNN
# n_neighbors = number of neighbors for KNN (k)
# weights = how to determine closeness between instances
# metric = how to calculate the weights
parameters = {
    'knn__n_neighbors': range(1, 26),
    'knn__weights': ['uniform', 'distance'],
    'knn__metric': ['manhattan', 'euclidean']
}

# Performing GridSearchCV and fitting the data
knn_grid = GridSearchCV(
    estimator=knn_pipeline,
    param_grid=parameters,
    scoring='accuracy',
    cv=cross_validation,
    n_jobs=-1,
    verbose=2
)
knn_grid.fit(fire_data_x, fire_data_y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=2, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=3, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=4, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=5, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=1, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=6, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=7, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=uniform; total time=   0.0s[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=distance; total time=   0.0s

[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=9, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=8, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=10, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=12, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=11, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=13, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=14, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=15, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=17, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=21, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=21, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=16, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=20, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=21, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=20, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=18, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=21, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=20, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=23, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=23, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=19, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=21, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=24, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=20, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=23, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=21, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=22, knn__weights=uniform; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=20, knn__weights=distance; total time=   0.0s
[CV] END knn__metric=manhattan, knn__n_neighbors=24, knn__weights=uniform; total time=   0.0s

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('knn', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'knn__metric': ['manhattan', 'euclidean'],
                         'knn__n_neighbors': range(1, 26),
                         'knn__weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=2)

In [7]:
# Getting the best parameters from GridSearchCV
print('Best parameters ', knn_grid.best_params_)
BEST_KNN_CLF = knn_grid.best_estimator_

Best parameters  {'knn__metric': 'manhattan', 'knn__n_neighbors': 19, 'knn__weights': 'distance'}

### Cross Validation Evaluation
- Getting the cross validation scores from the classifier and data
- Printing the mean and standard deviation of the scores

In [8]:
final_scores = cross_val_score(
    BEST_KNN_CLF,
    fire_data_x,
    fire_data_y,
    scoring='accuracy',
    cv=cross_validation,
)

# Showing each cross evaluation accuracy score
for i, score in enumerate(final_scores):
    print(f"CV {i+1} Score: {round(score*100,4)}%")

# Printing mean and standard deviation
print(f"CV Mean: {round(final_scores.mean()*100,4)}%")
print(f"CV Std: {round(final_scores.std()*100,4)}")

CV 1 Score: 89.7959%
CV 2 Score: 95.9184%
CV 3 Score: 95.9184%
CV 4 Score: 93.75%
CV 5 Score: 95.8333%
CV Mean: 94.2432%
CV Std: 2.3733

### Final Predictions and Accuracy
- Getting the predictions with cross_val_predict
- Output metrics

In [9]:
knn_predict_y = cross_val_predict(BEST_KNN_CLF, fire_data_x, fire_data_y, cv=cross_validation)

In [10]:
# Calculating metrics
classification_accuracy = round(accuracy_score(fire_data_y, knn_predict_y) * 100, 4)
confusion_matrix = confusion_matrix(fire_data_y, knn_predict_y)
per_class_classification = classification_report(fire_data_y, knn_predict_y)

In [11]:
# Output Metrics
print(f"Classification Accuracy: {classification_accuracy}")
print(f"Confusion Matrix:\n {confusion_matrix}")
print(f"Classification Report:\n {per_class_classification}")

Classification Accuracy: 94.2387
Confusion Matrix:
 [[133   4]
 [ 10  96]]
Classification Report:
               precision    recall  f1-score   support

        fire       0.93      0.97      0.95       137
    not fire       0.96      0.91      0.93       106

    accuracy                           0.94       243
   macro avg       0.95      0.94      0.94       243
weighted avg       0.94      0.94      0.94       243